# Generated by Django 3.2.7 on 2022-01-03 11:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=datetime.datetime(2022, 1, 3, 11, 42, 48, 729264, tzinfo=utc), max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
